### PR TITLE
Remove restriction on vc version

### PR DESCRIPTION
**Pull request by guyer**
Need a vc 9 build on Windows for compatibility with PySparse

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by guyer** [comment]
@conda-forge-admin, please rerender

**Comment by guyer** [comment]
@conda-forge-admin, please rerender

**Comment by guyer** [comment]
@conda-forge-admin, please rerender

**Comment by guyer** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by matthiasdiener** [comment]
Not sure if this PR is still relevant, but it is ready for review @guyer @isuruf

**Comment by matthiasdiener** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
