### PR TITLE
add ppc64le / arm64 support

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by matthiasdiener** [comment]
This is ready for review @guyer .

**Comment by isuruf** [comment]
@matthiasdiener, can you add yourself as a maintainer?

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@conda-forge/core, can you review and merge?

**Pull request merged**
